default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['DEV_DATABASE_USERNAME'] %>
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DEV_DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
